code_projects = [
    {
        'name':'Form to PDF Python Program',
        'description':"Program that lets the user import a CSV of questions and options into this program, answer the questions, export a PDF of the filled out form. I've built this as a base for a project I'm building for a relative who has to fill out the same form every other week who's just editing PDFs all the time, hopefully this makes things easier. I'm going to make a private fork off of this so I can specify it to their situation. Any part that I looked up a lot for I put the link in the code right near it",
        'skills':'Python (Programming Language) · Tkinter',
        'src':'./static/assets/code/formToPdf.png',
        'alt':'Plain form with example questons and answers. Black text on a gray background.',
        'link':'https://github.com/SarahYaw/simpleFormToPDF',
        'caption':"Thisis built in python using tkinter for the UI.",

    },
    {
        'name':'Medication Manager React.js Project',
        'description':"Webpage that allows you to enter medications for it to track when you're due for a refill, how often you take it, who prescribed it, etc. Has a basic LoopBack.io back-end that gives you a CRUD interface for a table of entries.",
        'skills':'React.js · Tailwind CSS · TypeScript · LoopBack.io',
        'src':'./static/assets/code/medManager.png',
        'alt':'Chart listing med name, dosage, description, morning dose, afternoon dose, evening dose, provider, last refilled, and buttons to refill, edit, and remove the medication from the list',
        'link':'https://github.com/SarahYaw/MedManager',
        'caption':'A reatively at-a-glance spreadsheet page to keep track of their medications.',
    },
    {
        'name':'AudioAI',
        'description':"Web application that allows users to use LLM's and AI voice software to create novel renditions of spec spots and other segments to fill air time. Connects to quite a few different automation softwares to air the tracks on-time.",
        'skills':'HTML · Cascading Style Sheets (CSS) · JavaScript · Vue.js · Bootstrap (Framework) · Application Programming Interfaces (API) · Python (Programming Language) · TypeScript · Django',
        'src':'./static/assets/code/audioai.png',
        'alt':'audio ai user interface showing the various adjustments one can make to a voice.',
        'link':'https://futurimedia.com/solutions/audioai/',
        'caption':'AI empowered web software that allows instantaneous production of audio commercials, spec spots, and other clips to be played over radio.',
    },
    {
        'name':'Beacon',
        'description':'This beacon mobile application is what the end-users will interact with. I did work on the administrative web application, but that is not open to the general public.',
        'skills':'HTML · Cascading Style Sheets (CSS) · JavaScript · Vue.js · Vutify ·  Bootstrap (Framework) · Application Programming Interfaces (API) · Python (Programming Language) · TypeScript · Django',
        'src':'../static/assets/code/beacon.png',
        'alt':'beacon mobile application.',
        'link':'https://www.beaconalwayson.com/',
        'caption':'Safety alert system that sends audio and text emergency and warning alerts via radio and downloadable mobile application by location from multiple official sources.',
    },
    {
        'name':'SpotOn',
        'description':"Web application that allows users to use LLM's and AI voice software to create novel renditions of spec spots and other segments to fill air time.",
        'skills':'HTML · Cascading Style Sheets (CSS) · JavaScript · Vue.js · Vutify ·  Bootstrap (Framework) · Application Programming Interfaces (API) · Python (Programming Language) · TypeScript · Django',
        'src':'../static/assets/code/spoton.png',
        'alt':'Spot On user interface showing a soundwave under the header Current Spot, and options to manage the spec spot and adjust audio levels.',
        'link':'https://futurimedia.com/solutions/spoton/',
        'caption':'One-Click spec spots and audio commercials.',
    },
    {
        'name': 'Crop Yield Predictor',
        'description': 'Program that predicts crop yields for Bay County Michigan given precipitation, temperature, and yield data from previous years. This was a project for my Big Data class. The focus was on handling large amounts of data and managing it efficiently.',
        'skills': 'Java · Data Analysis',
        'src':'../static/assets/code/cropYield.jpg',
        'alt': 'Poster showing the project details of the crop yield program.',
        'link':'https://www.facebook.com/share/p/1Cgkuxb2fD/',
        'caption':'Presentation poster I made for the Undergraduate Symposium to present this project.',
    }
]
art_projects = [
    {
        'name':'Peer Review Cross Stitch',
        'description':'This was a project I made for a friend of mine for getting his doctorate! He worked really hard for it and we both have a similar love for research for fun and silly inspirational quotes',
        'skills':'Cross Stitch · Embroidery · Counting',
        'src':'../static/assets/art/peerReviewCrossStitch.jpg',
        'alt':'cross stitch of a wreath of leaves in different shades of green around a quote that reads "I can do all things through evidence based best practice which strengthens me. peer review 24:7"',
        'caption':"Pardon the glare in the glass, it was tricky getting an image that the glass didn't totally reflect back!",
    },
    {
        'name':'Papier-mâché Pumpkin Head',
        'description':"I made this by filling a grocery bag with a bunch of other grocery bags and tying it so there were sectioned ridges, then papier-mâché-ing over that. Each layer took 24 hours to dry so I worked on it a little each day until I was happy with it. I then painted and carved it to look like Jack from the Animal Crossing franchise because even if the kids don't recognise him, he's not particularly scary. Eventually I want to add some kind of netting or fabric on the inside so it's harder to see me in there haha.",
        'skills':'Papier-mâché · Painting · Carving',
        'src':'../static/assets/art/pumpkinHead.jpg',
        'alt':'Papier-mâché pumpkin head on a person. It is carved into a smile.',
        'caption':'Me as a Pumpkin Guy for halloween while passing out candy at my gransparents house',
    },
    {
        'name':'Able Sisters Tissue Box Cover',
        'description':'This is a cardboard tissue box cover made to look like the Able Sisters store in Animal Crossing New Horizons. I grew up playing games in the Animal Crossing franchise and had a free weekend and a lot of cardboard from the holidays. The cardboard is held together by regular school glue and painted with acrylic paint.',
        'skills':'Painting · Cardboard · Planning',
        'src':'../static/assets/art/tissueCoverAbleSisters.jpg',
        'alt':"Tissue box cover that looks like the Able Sisters store from Animal Crossing New Horizons. It's a building with red siding, a green shingled roof, and white trim. There's a sign above the door that reads Able Sisters and has a green striped awning under that sign. On the left side of the front there's a display window with a mannequin and some spools of thread. ",
        'caption':'I grew up playing games in the Animal Crossing franchise and Able Sisters was always my favorite store',
    },
    
    {
        'name':'Flower Hat',
        'description':'I like plants of many kinds and sewing and collecting baseball caps, so I made this cute hat about it.',
        'skills':'Planning · Embroidery',
        'src':'../static/assets/art/flowerHat.png',
        'alt':"Various flowers embroidered on to a dark blue denim baseball cap. ",
        'caption':"Dollar Tree sometimes sells plain baseball caps. They're pretty good for embroidery",
    },
    
    {
        'name':'Bead Plant',
        'description':"Apparently there's a trend of making plants out of beads. I saw a few online and thought it would be the perfect little gift for my friend. We both like plants and one of the rooms in her new condo gets great sun, so I had to jump on the bandwagon",
        'skills':'Planning · Beading · Jewelry Making',
        'src':'../static/assets/art/beadPlant.png',
        'alt':"A small string of pearls plant made out of translucent seed beads. The plant sits in a clear pot with translucent resin as the dirt and three chains attached so it can be hung up. ",
        'caption':'I made this bead plant for my friends birthday.',
    },
]
timeline_items_1 = [
    {
        'title':'IT/Developer & Systems Analyst',
        'employer':'Rock Solid Logistics, Inc.',
        'duration': 'Jun 2025 - Present',
        'location': 'United States · Remote',
        'description': "During my time here I  am responsible for all tech related issues and advances. This involves maintaining and improving Rock Solid's website and customer-facing digital tools, development and management of internal dashboards to improve broker and dispatcher workflow., troubleshooting and tech support as issues arise",
        'skills': 'Application Development · Application Programming Interfaces (API) · Back-End Web Development · Bootstrap (Framework) · Cascading Style Sheets (CSS) · Communication · Database Design · Front-End Development · Full-Stack Development · Git · Graphic Design · HTML · HTML5 · JavaScript · Databases · Problem Solving · Programming · Programming Languages · Project Development · Project Planning · Requirements Gathering · SQL · Software Development · User Experience (UX) · User Interface Design · Visual Studio · Web Application Development · Web Applications · Web Development · Wireframing · Google Cloud Suite',
        'bar_tags':'one four_month timeline-event orange current',
        'card_tags':'orange current',
        'id': 'it'
    },
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event one_month',
        'card_tags':'empty',
    },
    {
        'link': 'https://github.com/SarahYaw/simpleFormToPDF',
        'title': 'Simple Form To PDF Program',
        'employer':'Project',
        'duration':'Mar 2025 - Apr 2025',
        'description': 'Import a csv of questions and answers into this program, answer the questions, export a pdf of the filled out form. I made this for a relative that fills out the same form weekly and struggles with making it look nice on the PDF form so this is an effort to auto-generate the PDF so they can just click done and email it off.',
        'skills': 'Python (Programming Language) · Tkinter · Project Planning · Application Development · Requirements Gathering',
        'bar_tags':'one one_month timeline-event',
        'card_tags':'',
        'id': 'pdf'
    },
    {
        'title': 'Full-stack Developer',
        'employer':'Futuri',
        'duration':'Mar 2022 - Mar 2025',
        'location':'United States · Remote',
        'description': 'Development and maintenance across multiple software projects. Most using a Vue.js frontend and Django python or a PHP backend.',
        'skills': 'Front-End Development · HTML · REST APIs · Python · Back-End Web Development · Vuetify · TypeScript · Communication · Web Applications · HTML5 · Full-Stack Development · Jira · Problem Solving · Django REST Framework · Trello · Application Development · User Interface Design · JavaScript · PHP · Programming Languages · Software Development · Web Application Development · Git · Project Development · Software as a Service (SaaS) · Django · Visual Studio · Cascading Style Sheets (CSS) · Node.js · Database Design · Web Development · User Experience (UX) · Wireframing · Application Programming Interfaces (API) · Vue.js · GitHub',
        'bar_tags':'one thirty_seven_month timeline-event purple',
        'card_tags':'purple',
        'id': 'fsdev'
    },
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event two_month',
        'card_tags':'empty',
    },
    {
        'title': "Master's degree, Computer Science",
        'location': 'Eastern Michigan University',
        'duration': 'Sep 2020 - Dec 2021',
        'description':"Due to keeping a 3.9ish average, I was eligible for a Graduate Assistant position, which pays for your graduate school curriculum along with an hourly pay. Because of that, I covered my grad tuition and boarding as well. I was off-handedly offered the chance to teach an undergrad introductory class, but the 2020 pandemic happened and the univerity stuck with their staff for teaching.",
        'bar_tags':'one sixteen_month timeline-event green',
        'card_tags':'green',
        'id': 'masters'
    },
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event four_month',
        'card_tags':'empty',
    },
    {
        'title': "Bachelors of Science degree, Computer Science",
        'employer': 'Minor in Mathematics',
        'location': 'Eastern Michigan University',
        'duration': 'Sep 2016 - Apr 2020',
        'description': "I'm pretty shy talking about it, but I was lucky enough to get a full ride scholarship for undergrad. Because of that, I was able to take some 'for fun' classes as well! Those include watercolor, graphic design, astronomy, and botany classes and more.",
        'bar_tags':'one fourty_four_month timeline-event green',
        'card_tags':'green',
        'id': 'bachelors'
    }
]
timeline_items_2 = [
    {
        'link': 'https://github.com/SarahYaw/PortfolioSite',
        'title': 'Portfolio Site',
        'employer':'Project',
        'duration':'Aug 2025 - Present',
        'description': "Just a nice little portfolio website to show off projects and summaries, you're looking at it now! ヾ(＾∇＾)",
        'skills': 'HTML · CSS · JavaScript · Python · Python Flask · Web Applications · User Interface Design · Git · Visual Studio · User Experience (UX)',
        'bar_tags':'two two_month timeline-event',
        'card_tags':'',
        'id': 'portfolio'
    },
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event three_month',
        'card_tags':'empty',
    },
    {
        'link': 'https://github.com/SarahYaw/MedManager',
        'title': 'Medication Manager',
        'employer':'Project',
        'duration':'Apr 2025 - May 2025',
        'description': "Webpage that allows you to enter meds for it to track when you're due for a refill, how often you take what dosage, who prescribed it, etc.",
        'skills': 'React.js · Node.js · Tailwind CSS · TypeScript · User Interface Design · LoopBack.io',
        'bar_tags':'two one_month timeline-event',
        'card_tags':'',
        'id': 'meds'
    },
    {
        'link': "https://futurimedia.com/solutions/audioai/",
        'title': 'AudioAI',
        'employer':'Project',
        'duration':'Apr 2022 - Mar 2025',
        'description': 'AI empowered web software that allows instantaneous production of audio commercials, spec spots, and other clips to be played over radio.',
        'skills': 'GitHub · Wireframing · Node.js · Visual Studio · Web Applications · Communication · Bootstrap (Framework) · Web Application Development · Front-End Development · Software as a Service (SaaS) · JavaScript · Application Development · Full-Stack Development · Application Programming Interfaces (API) · Cascading Style Sheets (CSS) · Git · TypeScript · Django · Project Development · REST APIs · Programming Languages · Software Development · User Experience (UX) · Python (Programming Language) · Back-End Web Development · HTML · Vue.js · Programming · Web Development',
        'bar_tags':'two thirty_six_month timeline-event purple light',
        'card_tags':'purple light',
        'id': 'aai'
    },
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event three_month',
        'card_tags':'empty',
    },
    {
        'title': 'Graduate Assistant',
        'employer': 'Eastern Michigan University',
        'duration': 'Sep 2020 - Dec 2021',
        'location': 'Ypsilanti, Michigan, United States',
        'description':'As a Graduate Assistant, I was responsible for grading and doing what I could to help the students learn the curriculum. I gave feedback on learning goal progression, assisted students during class with learning to code as well as any technical difficulties, assisted in development of assignments that ensure a solid understanding of foundational concepts for the class, and hosted tutoring hours outside of normal class functioning to assist other students with any questions they may have.',
        'skills':'Communication · Computer Science · Java · Problem Solving · Teaching · Programming Languages · Node.js',
        'bar_tags':'two sixteen_month timeline-event green',
        'card_tags':'green',
        'id': 'GA'
    }, 
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event four_month',
        'card_tags':'empty',
    },
    {
        'title': 'Graphic Designer',
        'employer': 'The Honors College at Eastern Michigan University · Part-time',
        'duration': 'Sep 2017 - Apr 2020',
        'location': 'Ypsilanti, Michigan, United States',
        'description': "During my time as the graphic designer at EMU's The Honors College, I did a lot of different tasks to keep up to date with the latest requirements. I collaborated with the programming team to create printed event flyers and social media graphics, collaborated with the computing team to create accessible user interfaces for applications,  designed pamphlets to advertise and inform students about various events being hosted by The Honors College,  drafted scholarship application forms to ensure efficient and accessible application and data entry, and helped promote The Honors College to the students at EMU in an appealing and accessible way.",
        'skills': 'Communication · Social Media · Teaching · Graphic Design · Social Media Graphic Design',
        'bar_tags':'two thirty_two_month timeline-event green',
        'card_tags':'green',
        'id': 'graphics'
    },
]
timeline_items_3 = [
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event six_month',
        'card_tags':'empty',
    },
    {
        'link': 'https://futurimedia.com/solutions/spoton/',
        'title': 'SpotOn',
        'employer':'Project',
        'duration':'Aug 2022 - Mar 2025',
        'description': 'One-Click spec spots and audio commercials. The goal of this project was to make a technology that allows radio talent to submit their voice for AI voice replication and have the machine read their commercials so they can focus on the content of the show.',
        'skills': 'GitHub · Wireframing · Node.js · Visual Studio · Web Applications · Communication · Bootstrap (Framework) · Web Application Development · Front-End Development · Software as a Service (SaaS) · JavaScript · Application Development · Full-Stack Development · Application Programming Interfaces (API) · Cascading Style Sheets (CSS) · Git · TypeScript · Django · Project Development · REST APIs · Programming Languages · Software Development · User Experience (UX) · Python (Programming Language) · Back-End Web Development · HTML · Programming · Web Development',
        'bar_tags':'three thirty_two_month timeline-event purple light',
        'card_tags':'purple light',
        'id': 'spoton'
    },
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event eleven_month',
        'card_tags':'empty',
    },
    {
        'title': 'Web Design Intern',
        'employer': 'Rock Solid Logistics, Inc. · Internship',
        'duration': 'Apr 2021 - Aug 2021',
        'location': 'Brighton, Michigan, United States',
        'description': 'During my time here I re-built the company website using Drupal and communicated with different employees beyond the owners to ensure a well-rounded design that advertised the company as they wanted.',
        'skills': 'Communication · Problem Solving · Project Development · Programming · Wireframing',
        'bar_tags':'three five_month timeline-event orange',
        'card_tags':'orange',
        'id': 'intern'
    },
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event eleven_month',
        'card_tags':'empty',
    },
    {
        'title': 'Teaching Assistant',
        'employer': 'Eastern Michigan University',
        'duration': 'Jan 2020 - Apr 2020',
        'location': 'Ypsilanti, Michigan, United States',
        'description': 'I was a teaching assistant for a semester in an introductory computer science class. This involved grading homework assignments and projects to give feedback on learning goal progression, assisting students during class with learning to code as well as any technical difficulties, and assisting in development of assignments that ensure a solid understanding of foundational concepts for the class.',
        'skills': 'Communication · Computer Science · HTML5 · Java · Problem Solving · JavaScript · Programming Languages · Cascading Style Sheets (CSS)',
        'bartags':'three four_month timeline-event green',
        'card_tags':'grteen',
        'id': 'TA'
    },
    {
        'link': 'https://github.com/crypt0d1v3r/Checkers',
        'title': 'Checkers AI',
        'employer': 'Project',
        'duration': 'Sep 2019 - Dec 2019',
        'description': 'A program that uses AI principals to play checkers against the user. I chiefly did the user Interface for this project.',
        'skills': ' Java · GitHub · Communication · Git · Software Development · Graphic Design · Programming',
        'bar_tags':'four three_month timeline-event green light',
        'card_tags':'green light',
        'id': 'checkers'
    },
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event fourteen_month',
        'card_tags':'empty',
    },
    {
        'title': 'Teaching Assistant',
        'employer': 'Eastern Michigan University',
        'duration': 'Jun 2018 - Jun 2018',
        'location': 'Ypsilanti, Michigan, United States',
        'description': 'Teaching assistant for a week-long camp called Bits&Bytes. We taught middle school students basic computer science concepts to introduce them to STEM career choices. This involved creating lesson plans that teach introductory concepts and skills and maintain engagement at a middle school level.',
        'skills': 'HTML · Communication · Computer Science · Java · Problem Solving · Teaching · Programming Languages',
        'bar_tags':'four zero_month timeline-event',
        'card_tags':'',
        'id': 'camp'
    },
]
timeline_items_4 = [
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event six_month',
        'card_tags':'empty',
    },
    {
        'link': 'https://futurimedia.com/solutions/beacon/',
        'title': 'Beacon',
        'employer':'Project',
        'duration':'Mar 2024 - Mar 2025',
        'description': 'Safety alert system that sends audio and text emergency and warning alerts via radio and downloadable mobile application by location from multiple official sources.',
        'skills': 'GitHub · Wireframing · Node.js · Visual Studio · Web Applications · Communication · Vuetify · Web Application Development · Front-End Development · Software as a Service (SaaS) · Application Development · Full-Stack Development · Cascading Style Sheets (CSS) · Git · Project Development · REST APIs · Programming Languages · Software Development · User Experience (UX) · Python (Programming Language) · HTML · Vue.js · Programming · Web Development',
        'bar_tags':'four thirteen_month timeline-event purple light',
        'card_tags':'purple light',
        'id': 'beacon'
    }, 
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event thirty_four_month',
        'card_tags':'empty',
    },
    {
        'link': 'https://github.com/SarahYaw/PRNG',
        'title': 'Pseudo-Random Number Generator',
        'employer': 'Project',
        'duration': 'Jan 2021 - Apr 2021',
        'description': 'A program of different PRNG algorithms researched and coded up for an Independent Study.',
        'skills': 'Java · GitHub · Computer Science · Programming',
        'bar_tags':'four four_month timeline-event green light',
        'card_tags':'green light',
        'id': 'prng'
    },
    {
        'link': '',
        'title': '',
        'employer':'',
        'duration':'',
        'description': '',
        'skills': '',
        'bar_tags':'empty timeline-event eight_month',
        'card_tags':'empty',
    },
    {
        'link':'https://www.facebook.com/share/p/1Cgkuxb2fD/',
        'title': 'Crop Yield Predictor',
        'employer': 'Project',
        'duration': 'Jan 2020 - Apr 2020',
        'description': 'Program that predicts crop yields for Bay County Michigan given precipitation, temperature, and yield data from previous years. This was a project for my Big Data class. The focus was on handling large amounts of data and managing it efficiently.',
        'skills': 'Java · GitHub · Computer Science · Software Development · Programming',
        'bar_tags':'four four_month timeline-event green light',
        'card_tags':'green light',
        'id': 'crops'
    },
]
mobile_timeline = [
    {
        'link': 'https://github.com/SarahYaw/PortfolioSite',
        'title': 'Portfolio Site',
        'employer':'Project',
        'duration':'Aug 2025 - Present',
        'description': "Just a nice little portfolio website to show off projects and summaries, you're looking at it now! ヾ(＾∇＾)",
        'skills': 'HTML · CSS · JavaScript · Python · Python Flask · Web Applications · User Interface Design · Git · Visual Studio · User Experience (UX)',
        'tags':'two two_month timeline-event'
    },
    {
        'link': 'https://github.com/SarahYaw/MedManager',
        'title': 'Medication Manager',
        'employer':'Project',
        'duration':'Apr 2025 - May 2025',
        'description': "Webpage that allows you to enter meds for it to track when you're due for a refill, how often you take what dosage, who prescribed it, etc.",
        'skills': 'React.js · Node.js · Tailwind CSS · TypeScript · User Interface Design · LoopBack.io',
        'tags':'two one_month timeline-event'
    },
    {
        'link': 'https://github.com/SarahYaw/simpleFormToPDF',
        'title': 'Simple Form To PDF Program',
        'employer':'Project',
        'duration':'Mar 2025 - Apr 2025',
        'description': 'Import a csv of questions and answers into this program, answer the questions, export a pdf of the filled out form. I made this for a relative that fills out the same form weekly and struggles with making it look nice on the PDF form so this is an effort to auto-generate the PDF so they can just click done and email it off.',
        'skills': 'Python (Programming Language) · Tkinter · Project Planning · Application Development · Requirements Gathering',
        'tags':'one one_month timeline-event'
    },
    {
        'title':'IT/Developer & Systems Analyst',
        'employer':'Rock Solid Logistics, Inc.',
        'duration': 'Jun 2025 - Present',
        'location': 'United States · Remote',
        'description': "During my time here I  am responsible for all tech related issues and advances. This involves maintaining and improving Rock Solid's website and customer-facing digital tools, development and management of internal dashboards to improve broker and dispatcher workflow., troubleshooting and tech support as issues arise",
        'skills': 'Application Development · Application Programming Interfaces (API) · Back-End Web Development · Bootstrap (Framework) · Cascading Style Sheets (CSS) · Communication · Database Design · Front-End Development · Full-Stack Development · Git · Graphic Design · HTML · HTML5 · JavaScript · Databases · Problem Solving · Programming · Programming Languages · Project Development · Project Planning · Requirements Gathering · SQL · Software Development · User Experience (UX) · User Interface Design · Visual Studio · Web Application Development · Web Applications · Web Development · Wireframing · Google Cloud Suite',
        'tags':'one four_month timeline-event orange current'
    },
    {
        'title': 'Full-stack Developer',
        'employer':'Futuri',
        'duration':'Mar 2022 - Mar 2025',
        'location':'United States · Remote',
        'description': 'Development and maintenance across multiple software projects. Most using a Vue.js frontend and Django python or a PHP backend.',
        'skills': 'Front-End Development · HTML · REST APIs · Python · Back-End Web Development · Vuetify · TypeScript · Communication · Web Applications · HTML5 · Full-Stack Development · Jira · Problem Solving · Django REST Framework · Trello · Application Development · User Interface Design · JavaScript · PHP · Programming Languages · Software Development · Web Application Development · Git · Project Development · Software as a Service (SaaS) · Django · Visual Studio · Cascading Style Sheets (CSS) · Node.js · Database Design · Web Development · User Experience (UX) · Wireframing · Application Programming Interfaces (API) · Vue.js · GitHub',
        'tags':'one thirty_seven_month timeline-event purple'
    },
    {
        'link': 'https://futurimedia.com/solutions/spoton/',
        'title': 'SpotOn',
        'employer':'Project',
        'duration':'Aug 2022 - Mar 2025',
        'description': 'One-Click spec spots and audio commercials. The goal of this project was to make a technology that allows radio talent to submit their voice for AI voice replication and have the machine read their commercials so they can focus on the content of the show.',
        'skills': 'GitHub · Wireframing · Node.js · Visual Studio · Web Applications · Communication · Bootstrap (Framework) · Web Application Development · Front-End Development · Software as a Service (SaaS) · JavaScript · Application Development · Full-Stack Development · Application Programming Interfaces (API) · Cascading Style Sheets (CSS) · Git · TypeScript · Django · Project Development · REST APIs · Programming Languages · Software Development · User Experience (UX) · Python (Programming Language) · Back-End Web Development · HTML · Programming · Web Development',
        'tags':'three thirty_two_month timeline-event purple light'
    },
    {
        'link': "https://futurimedia.com/solutions/audioai/",
        'title': 'AudioAI',
        'employer':'Project',
        'duration':'Apr 2022 - Mar 2025',
        'description': 'AI empowered web software that allows instantaneous production of audio commercials, spec spots, and other clips to be played over radio.',
        'skills': 'GitHub · Wireframing · Node.js · Visual Studio · Web Applications · Communication · Bootstrap (Framework) · Web Application Development · Front-End Development · Software as a Service (SaaS) · JavaScript · Application Development · Full-Stack Development · Application Programming Interfaces (API) · Cascading Style Sheets (CSS) · Git · TypeScript · Django · Project Development · REST APIs · Programming Languages · Software Development · User Experience (UX) · Python (Programming Language) · Back-End Web Development · HTML · Vue.js · Programming · Web Development',
        'tags':'two thirty_six_month timeline-event purple light'
    },
    {
        'link': 'https://futurimedia.com/solutions/beacon/',
        'title': 'Beacon',
        'employer':'Project',
        'duration':'Mar 2024 - Mar 2025',
        'description': 'Safety alert system that sends audio and text emergency and warning alerts via radio and downloadable mobile application by location from multiple official sources.',
        'skills': 'GitHub · Wireframing · Node.js · Visual Studio · Web Applications · Communication · Vuetify · Web Application Development · Front-End Development · Software as a Service (SaaS) · Application Development · Full-Stack Development · Cascading Style Sheets (CSS) · Git · Project Development · REST APIs · Programming Languages · Software Development · User Experience (UX) · Python (Programming Language) · HTML · Vue.js · Programming · Web Development',
        'tags':'four thirteen_month timeline-event purple light'
    },
    {
        'title': "Master's degree, Computer Science",
        'location': 'Eastern Michigan University',
        'duration': 'Sep 2020 - Dec 2021',
        'description':"Due to keeping a 3.9ish average, I was eligible for a Graduate Assistant position, which pays for your graduate school curriculum along with an hourly pay. Because of that, I covered my grad tuition and boarding as well. I was off-handedly offered the chance to teach an undergrad introductory class, but the 2020 pandemic happened and the univerity stuck with their staff for teaching.",
        'tags':'one sixteen_month timeline-event green'
    },
    {
        'link': 'https://github.com/SarahYaw/PRNG',
        'title': 'Pseudo-Random Number Generator',
        'employer': 'Project',
        'duration': 'Jan 2021 - Apr 2021',
        'description': 'A program of different PRNG algorithms researched and coded up for an Independent Study.',
        'skills': 'Java · GitHub · Computer Science · Programming',
        'tags':'four four_month timeline-event green light'
    },
    {
        'title': 'Web Design Intern',
        'employer': 'Rock Solid Logistics, Inc. · Internship',
        'duration': 'Apr 2021 - Aug 2021',
        'location': 'Brighton, Michigan, United States',
        'description': 'During my time here I re-built the company website using Drupal and communicated with different employees beyond the owners to ensure a well-rounded design that advertised the company as they wanted.',
        'skills': 'Communication · Problem Solving · Project Development · Programming · Wireframing',
        'tags':'three five_month timeline-event orange'
    },
    {
        'title': 'Graduate Assistant',
        'employer': 'Eastern Michigan University',
        'duration': 'Sep 2020 - Dec 2021',
        'location': 'Ypsilanti, Michigan, United States',
        'description':'As a Graduate Assistant, I was responsible for grading and doing what I could to help the students learn the curriculum. I gave feedback on learning goal progression, assisted students during class with learning to code as well as any technical difficulties, assisted in development of assignments that ensure a solid understanding of foundational concepts for the class, and hosted tutoring hours outside of normal class functioning to assist other students with any questions they may have.',
        'skills':'Communication · Computer Science · Java · Problem Solving · Teaching · Programming Languages · Node.js',
        'tags':'two sixteen_month timeline-event green bottom-half'
    }, 
    {
        'title': "Bachelors of Science degree, Computer Science",
        'employer': 'Minor in Mathematics',
        'location': 'Eastern Michigan University',
        'duration': 'Sep 2016 - Apr 2020',
        'description': "I'm pretty shy talking about it, but I was lucky enough to get a full ride scholarship for undergrad. Because of that, I was able to take some 'for fun' classes as well! Those include watercolor, graphic design, astronomy, and botany classes and more.",
        'tags':'one fourty_four_month timeline-event green'
    },
    {
        'title': 'Graphic Designer',
        'employer': 'The Honors College at Eastern Michigan University · Part-time',
        'duration': 'Sep 2017 - Apr 2020',
        'location': 'Ypsilanti, Michigan, United States',
        'description': "During my time as the graphic designer at EMU's The Honors College, I did a lot of different tasks to keep up to date with the latest requirements. I collaborated with the programming team to create printed event flyers and social media graphics, collaborated with the computing team to create accessible user interfaces for applications,  designed pamphlets to advertise and inform students about various events being hosted by The Honors College,  drafted scholarship application forms to ensure efficient and accessible application and data entry, and helped promote The Honors College to the students at EMU in an appealing and accessible way.",
        'skills': 'Communication · Social Media · Teaching · Graphic Design · Social Media Graphic Design',
        'tags':'two thirty_two_month timeline-event green bottom-half'
    },
    {
        'title': 'Teaching Assistant',
        'employer': 'Eastern Michigan University',
        'duration': 'Jan 2020 - Apr 2020',
        'location': 'Ypsilanti, Michigan, United States',
        'description': 'I was a teaching assistant for a semester in an introductory computer science class. This involved grading homework assignments and projects to give feedback on learning goal progression, assisting students during class with learning to code as well as any technical difficulties, and assisting in development of assignments that ensure a solid understanding of foundational concepts for the class.',
        'skills': 'Communication · Computer Science · HTML5 · Java · Problem Solving · JavaScript · Programming Languages · Cascading Style Sheets (CSS)',
        'tags':'three four_month timeline-event green bottom-half'
    },
    {
        'link': 'https://github.com/crypt0d1v3r/Checkers',
        'title': 'Checkers AI',
        'employer': 'Project',
        'duration': 'Sep 2019 - Dec 2019',
        'description': 'A program that uses AI principals to play checkers against the user. I chiefly did the user Interface for this project.',
        'skills': ' Java · GitHub · Communication · Git · Software Development · Graphic Design · Programming',
        'tags':'four three_month timeline-event green light bottom-half'
    },
    {
        'link':'https://www.facebook.com/share/p/1Cgkuxb2fD/',
        'title': 'Crop Yield Predictor',
        'employer': 'Project',
        'duration': 'Jan 2020 - Apr 2020',
        'description': 'Program that predicts crop yields for Bay County Michigan given precipitation, temperature, and yield data from previous years. This was a project for my Big Data class. The focus was on handling large amounts of data and managing it efficiently.',
        'skills': 'Java · GitHub · Computer Science · Software Development · Programming',
        'tags':'four four_month timeline-event green light bottom-half'
    },
    {
        'title': 'Teaching Assistant',
        'employer': 'Eastern Michigan University',
        'duration': 'Jun 2018 - Jun 2018',
        'location': 'Ypsilanti, Michigan, United States',
        'description':
        '''
            Teaching assistant for a week-long camp called Bits&Bytes. We taught middle school students basic computer science concepts to introduce them to STEM career choices. This involved creating lesson plans that teach introductory concepts and skills and maintain engagement at a middle school level.
        ''',
        'skills': 'HTML · Communication · Computer Science · Java · Problem Solving · Teaching · Programming Languages',
        'tags':'four zero_month timeline-event bottom-half'
    },
]